[package]
name = "hydra-lang"
version = "0.1.0"
edition = "2024"
description = "A lexer and parser for the Hydra programming language"

[dependencies]

[[bin]]
name = "hydra-parser"
path = "src/main.rs"